### PR TITLE
e2e tests: bump up version of Astarte Cluster action and fix a related issue.

### LINKED ISSUE #142: e2e tests: new version of Astarte action and fix related bug.
An incorrect check for the result of the `POST` and `DELETE` commands is present in the end-to-end tests. 
The error printed [here](https://github.com/astarte-platform/astarte-device-sdk-rust/actions/runs/4105730310/jobs/7082999083#step:7:403) should lead to a test failure.
Furthermore, the error mentioned above is a bug in Astarte that has been fixed from `v1.0.4`. The GitHub action for the Astarte cluster is by default stuck at `v1.0.1`. It should be forcefully updated to `v1.0.4` in order to avoid an incorrect test failure.

### PR DESCRIPTION
**Pull request by sorru94**
Some fixes for the end to end tests:
- Handle correctly a failure of `POST` or `DELETE` HTTPS requests.
- Bump up version of Astarte in CI to `1.0.4`
- Removes the not necessary `ignore_ssl_errors` flag in the device initialization.

Closes #142

### CODE REVIEW

File: tests/e2etest/main.rs [hunk 1]
```diff
@@ -613,12 +620,15 @@ async fn http_post_to_intf(
...
         .send()
         .await
-        .map_err(|e| format!("HTTP POST failure: {e}"))?
-        .text()
-        .await
-        .map_err(|e| format!("Failure in parsing the HTTP POST result: {e}"))?;
-    if response != value_json {
-        println!("Server response: {response}");
+        .map_err(|e| format!("HTTP POST failure: {e}"))?;
+    if response.status() != 200 {
```
Comment (FrancescoVaiani) [inline tests/e2etest/main.rs:624]: Can we replace 200 with the Reqwest status code enum?
```suggestion
    if response.status() != StatusCode::Ok{
```

File: tests/e2etest/main.rs [hunk 2]
```diff
@@ -647,12 +657,15 @@ async fn http_delete_to_intf(
...
         .send()
         .await
-        .map_err(|e| format!("HTTP POST failure: {e}"))?
-        .text()
-        .await
-        .map_err(|e| format!("Failure in parsing the HTTP POST result: {e}"))?;
-    if !response.is_empty() {
-        println!("Server response: {response}");
+        .map_err(|e| format!("HTTP DELETE failure: {e}"))?;
+    if response.status() != 204 {
```
Comment (FrancescoVaiani) [inline tests/e2etest/main.rs:661]: Can we replace 204 with the Reqwest status code enum?
```suggestion
    if response.status() != StatusCode::NoContent{
```

**Review by FrancescoVaiani — CHANGES_REQUESTED** [review]
I could not remember what the status code 204 stands for. 
Maybe we can begin to slowly replace the status codes with the Reqwest StatusCode enum.

**Comment by sorru94** [comment]
> I could not remember what the status code 204 stands for. Maybe we can begin to slowly replace the status codes with the Reqwest StatusCode enum.

I noticed that in the `registration.rs` and `pairing.rs` modules we use `http::StatusCode` instead of `reqwest::StatusCode`.
I think it would be better to use the `reqwest::StatusCode` everywhere as we always compare to a result from `reqwest`.

**Review by harlem88 — APPROVED** [review]
